name: Staging Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/bda-be:latest
        docker push ${{ secrets.DOCKER_USER }}/bda-be:latest

  deploy:
    environment: staging
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client
      
    - name: Login via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        passphrase: ${{ secrets.PWD }}
        key: ${{ secrets.SSH_KEY }}
        script: | 
          whoami
          ls -la

    - name: Deploy to VPS
      run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
          docker pull ${{ secrets.DOCKER_USER }}/bda-be:latest
          docker stop bda-be || true
          docker rm bda-be || true
          docker run -d --name bda-be -p 5000:8000 ${{ secrets.DOCKER_USER }}/bda-be:latest
